export const memeBank = [
  "WiFi ছাড়া জীবন চলে না, কিন্তু brain offline থাকে 😭",
  "Google search করে ‘how to be smart fast’ 😂",
  "তোমার brain এর loading bar 99% এ আটকে গেছে ⏳",
  "NPC mode permanently ON 🤖",
  "Sleep schedule না, sleep disaster আছে 😴",
  "Phone battery low, ego battery full 🔋",
  "Common sense update pending… please wait 💀",
  "তুমি চলমান meme template 😂",
  "Read more করো, কিন্তু বুঝো কম 🤡",
  "Brain এ RAM কম, tab বেশি খোলা থাকে 🧠",
  "Life এ skip ad button থাকলে use করতে 😆",
  "Study mode ঢুকলেই crash খায় system 💻",
  "Face unlock তোমাকে চিনে না 😭",
  "Google Maps ও তোমাকে হারিয়ে ফেলে 🧭",
  "Confidence 100%, skill 2% 🔥",
  "Plan ছিল genius, execution ছিল disaster 💀",
  "You are the reason error 404 exists 😂",
  "Brain এ update আসে না, শুধু crash আসে 🤯",
  "Tension level always high voltage ⚡",
  "Sleep = full system reset 😴",
  "Life e buffering forever loading ⏳",
  "Logic কোথায় গেছে জানা নেই 🤡",
  "Study table আছে, study নাই 📚",
  "You are premium version of confusion 😂",
  "ChatGPT ও তোমাকে roast করতে ভয় পায় 😆",
  "Mind: ‘let’s do work’ → Body: ‘nope’ 😭",
  "Shortcut খুঁজতে গিয়ে road হারাও 🚶",
  "Memory card full কিন্তু useless data 📂",
  "Ego high, performance low 📉",
  "You are WiFi without internet 📶",
  "Brain: 1 core CPU, 100 tabs open 💻",
  "Life goal: survive daily 😂",
  "Alarm বাজে, কিন্তু তুমি sleep mode এ 😴",
  "Focus কোথায়? lost item 🔍",
  "Logic deleted permanently 💀",
  "You are loading… forever ⏳",
  "Study motivation expired 📆",
  "Talent missing, attitude installed 😆",
  "System error: common sense not found 🚫",
  "You are walking meme factory 😂",
  "Memory leak in brain 🧠",
  "Life = lagging game 🎮",
  "You are beta version of human 🤖",
  "Energy full, direction zero 🔥",
  "Brain stuck in airplane mode ✈️",
  "You think fast, act slow 🐢",
  "Confidence vs reality mismatch 💀",
  "You are offline Google search 😂",
  "Sleep debt increasing daily 😴",
  "Focus mode never activated ⚙️",
  "You are glitch in matrix 🌀",
  "Plan A-Z all failed 🤡",
  "Error: intelligence not installed 💻",
  "You are walking WiFi problem 📡",
  "Mind is empty but noisy 🤯",
  "You are human loading screen ⏳",
  "Life = endless buffering 😆",
  "You are premium confusion pack 💀",
  "Brain update failed ❌",
  "You are shortcut lover 🚀",
  "Reality check missing ⚠️",
  "You are funny accident 😂",
  "Sleep = main profession 😴",
  "You are lagging personality 🎮",
  "Study plan = theory only 📚",
  "You are broken algorithm 🤖",
  "Life execution failed 💀",
  "You are cloud of confusion ☁️",
  "Brain: low storage 🧠",
  "You are human bug report 🐞",
  "Focus = myth 🔍",
  "You are premium meme generator 😂",
  "Logic loading failed ⏳",
  "You are WiFi without password 📶",
  "Brain: demo version only 🧠",
  "You are chaos in human form 🤡",
  "Sleep mode activated permanently 😴",
  "You are accidental genius (sometimes) 🔥",
  "System overheating 🔥",
  "You are lag + crash combo 💀",
  "Life script not found 📜",
  "You are walking error message 🚫",
  "Brain: under maintenance 🛠️",
  "You are funny by default 😂",
  "Reality: not compatible with you ⚠️",
  "You are human beta tester 🤖",
  "Focus lost in translation 🧭",
  "You are unlimited confusion plan 😆",
  "Mind: empty but loud 📢",
  "You are meme-worthy always 😂"
];